import React, { useId, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ChevronDown, Users } from 'lucide-react'

export default function UserServiceMatrix({ section, users, Matrix, onOpen, reducedMotion }) {
  const [expandedUser, setExpandedUser] = useState('')
  const prefix = useId()
  const rows = users.map((user) => ({ ...user, section: user.yearSections.find((entry) => entry.year === section.year) }))
  return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
    <header className="flex items-center gap-3 border-b border-teal-100 bg-gradient-to-r from-teal-50 to-white px-6 py-5"><Users className="text-teal-700" /><div><h3 className="text-lg font-bold text-slate-900">User-wise service matrix · {section.year}</h3><p className="mt-1 text-xs text-slate-500">Manager Assigned to Staff counts, PO status and service closure for the selected financial year.</p></div></header>
    <div className="overflow-auto"><table className="w-full border-separate border-spacing-0 text-left text-sm"><thead><tr><th className="min-w-64 bg-slate-100 px-5 py-4 text-xs text-slate-700">Users</th><th className="min-w-28 bg-slate-100 px-4 py-4 text-xs text-slate-700">Allocated Overall</th><th className="min-w-28 bg-slate-100 px-4 py-4 text-xs text-slate-700">PO Received<small className="mt-1 block font-normal text-slate-500">Received / Allocated</small></th><th className="min-w-28 bg-slate-100 px-4 py-4 text-xs text-slate-700">PO Pending<small className="mt-1 block font-normal text-slate-500">Pending / Allocated</small></th><th className="min-w-32 bg-slate-100 px-4 py-4 text-xs text-slate-700">Clients in {section.year}<small className="mt-1 block font-normal text-slate-500">Selected FY / Allocated</small></th><th className="min-w-32 bg-slate-100 px-4 py-4 text-xs text-slate-700">PO Received in {section.year}<small className="mt-1 block font-normal text-slate-500">Received / Selected FY</small></th><th className="min-w-32 bg-slate-100 px-4 py-4 text-xs text-slate-700">Service Closed<small className="mt-1 block font-normal text-slate-500">Closed / PO Received</small></th>{section.services.map((service) => <th key={service} className="min-w-36 bg-slate-100 px-4 py-4 text-xs text-slate-700">{service}</th>)}</tr></thead><tbody>{rows.map((user, index) => {
      const expanded = expandedUser === user.userId
      const region = `${prefix}-${index}`
      const closedClients = user.section?.summary.clients || 0
      const selectedYearClients = user.allocatedClientsByYear?.[section.year] || 0
      const allocatedClients = user.allocatedClients || 0
      const poReceivedInYear = user.poReceivedClientsByYear?.[section.year] || 0
      const poReceivedClients = user.poReceivedClients || 0
      const poPendingClients = Math.max(0, allocatedClients - poReceivedClients)
      return <React.Fragment key={user.userId}><tr className={expanded ? 'bg-teal-50' : 'hover:bg-teal-50/50'}><td className="border-b border-slate-100 px-5 py-4"><button type="button" aria-expanded={expanded} aria-controls={region} onClick={() => setExpandedUser(expanded ? '' : user.userId)} className="flex w-full items-center justify-between gap-4 font-semibold text-teal-700"><span>{user.userName}<span className="mt-1 block text-left text-xs font-normal capitalize text-slate-500">{user.role}</span></span><ChevronDown size={16} className={`transition-transform duration-300 ${expanded ? 'rotate-180' : ''}`} /></button></td><td className="border-b border-slate-100 px-4 py-4 font-bold text-teal-800">{allocatedClients}</td><td className="border-b border-slate-100 px-4 py-4 font-bold text-emerald-700">{poReceivedClients} / {allocatedClients}</td><td className="border-b border-slate-100 px-4 py-4 font-bold text-amber-700">{poPendingClients} / {allocatedClients}</td><td className="border-b border-slate-100 px-4 py-4 font-bold text-teal-800"><span aria-label={`${selectedYearClients} clients in ${section.year} out of ${allocatedClients} allocated clients`}>{selectedYearClients} / {allocatedClients}</span></td><td className="border-b border-slate-100 px-4 py-4 font-bold text-emerald-700">{poReceivedInYear} / {selectedYearClients}</td><td className="border-b border-slate-100 px-4 py-4 font-bold text-emerald-700"><span aria-label={`${closedClients} closed services out of ${poReceivedInYear} PO received clients in ${section.year}`}>{closedClients} / {poReceivedInYear}</span></td>{section.services.map((service) => <td key={service} className="border-b border-slate-100 px-4 py-4 text-center text-indigo-700">{user.section?.clients.reduce((count, client) => count + (client.services[service] || 0), 0) || 0}</td>)}</tr><tr><td colSpan={section.services.length + 7} className="p-0"><AnimatePresence initial={false}>{expanded && <motion.div id={region} role="region" aria-label={`${user.userName} applicant types`} initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: reducedMotion ? 0 : .3 }} className="overflow-hidden"><div className="bg-teal-50/50 p-3 sm:p-5">{user.section?.summary.clients ? <Matrix section={user.section} onOpen={() => onOpen(user.section, user.userId)} reducedMotion={reducedMotion} /> : <p className="p-6 text-center text-sm text-slate-500">No clients with closed POs for this user in {section.year}.</p>}</div></motion.div>}</AnimatePresence></td></tr></React.Fragment>
    })}{!rows.length && <tr><td colSpan={section.services.length + 7} className="p-8 text-center text-slate-500">No users available in your scope.</td></tr>}</tbody></table></div>

  </section>
}
