const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function safeUrl(value) { try { const url = new URL(value); return url.protocol === 'https:' ? url.href : ''; } catch { return ''; } }
function buildDataWorkflowEmail({ title, moduleName, clientName, financialYear, actorName, recipientName, record, stage, message }) {
  const base = safeUrl(process.env.FRONTEND_URL || process.env.APP_URL || 'https://crmananttattva.vercel.app');
  const url = base ? new URL('/sales/client-master', base).href : '';
  const pending = ['manager_pending', 'excel_uploaded', 'compliance_pending'].includes(stage);
  const tone = stage.includes('rejected') ? '#be123c' : '#0f766e';
  const status = stage === 'manager_pending' ? 'Manager review pending' : stage === 'excel_uploaded' ? 'Excel upload complete' : stage === 'compliance_pending' ? 'Compliance review pending' : stage.includes('rejected') ? 'Changes requested' : 'Review complete';
  const files = [['Base Data', record.baseUpload], ['Portal Upload', record.portalUpload]].filter(([, file]) => file);
  const fileRows = files.map(([label,file]) => `<tr><td style="padding:16px 18px;border-bottom:1px solid #e2e8f0"><div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:1px">${escapeHtml(moduleName)} ${label}</div><div style="margin-top:5px;font-size:13px;font-weight:bold;color:#0f172a;word-break:break-all">${escapeHtml(file.originalName || file.name || 'Excel file')}</div><div style="margin-top:6px;font-size:12px;color:#64748b">${Number(file.importedRowCount || 0).toLocaleString('en-IN')} imported rows · ${Number(file.totalQuantity || 0).toLocaleString('en-IN', { maximumFractionDigits: 3 })} MT</div><span style="display:inline-block;margin-top:8px;font-size:11px;font-weight:bold;color:#047857">${file.importStatus === 'Imported' ? 'Imported successfully' : 'Upload saved'}</span></td></tr>`).join('');
  const detail = stage === 'manager_pending' ? 'Both Excel files have been saved and automatically submitted. Please review the client data in CRM.' : stage === 'excel_uploaded' ? 'Both Excel files have been uploaded. Open CRM to review the client workspace.' : message || title;
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#0f172a"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="640" cellpadding="0" cellspacing="0" style="width:100%;max-width:640px;background:#fff;border:1px solid #e2e8f0;border-radius:20px;overflow:hidden"><tr><td style="padding:28px 32px;background:#0f172a;border-top:5px solid ${tone}"><div style="font-size:11px;letter-spacing:3px;font-weight:bold;color:#5eead4">ANANTTATTVA CRM</div><h1 style="margin:12px 0 8px;font-size:25px;line-height:1.3;color:#fff">${escapeHtml(title)}</h1><span style="display:inline-block;padding:7px 12px;background:#134e4a;color:#99f6e4;border-radius:20px;font-size:11px;font-weight:bold">${escapeHtml(status)}</span></td></tr><tr><td style="padding:28px 32px"><p style="margin:0 0 12px;font-size:15px">Hello ${escapeHtml(recipientName || 'Team Member')},</p><p style="margin:0 0 24px;font-size:14px;line-height:1.7;color:#475569">${escapeHtml(detail)}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #ccfbf1;background:#f0fdfa;border-radius:12px"><tr><td style="padding:18px"><div style="font-size:10px;letter-spacing:1.5px;color:#0f766e;font-weight:bold">CLIENT WORKSPACE</div><div style="margin-top:8px;font-size:19px;line-height:1.4;font-weight:bold">${escapeHtml(clientName)}</div><div style="margin-top:12px;font-size:13px;color:#475569">Financial year <strong>${escapeHtml(financialYear)}</strong><br><span style="line-height:2">Updated by <strong>${escapeHtml(actorName)}</strong></span></div></td></tr></table>${files.length ? `<h2 style="margin:24px 0 10px;font-size:14px">Uploaded documents</h2><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:12px">${fileRows}</table>` : ''}${url ? `<table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:26px"><tr><td bgcolor="${tone}" style="border-radius:10px"><a href="${escapeHtml(url)}" style="display:inline-block;padding:14px 24px;color:#fff;text-decoration:none;font-size:13px;font-weight:bold">${pending ? 'Review data in CRM' : 'Open client workspace'} &rarr;</a></td></tr></table><p style="margin:14px 0 0;font-size:11px;line-height:1.6;color:#64748b">Open Client Master and select ${escapeHtml(clientName)} · FY ${escapeHtml(financialYear)}.</p>` : ''}</td></tr><tr><td style="padding:18px 32px;border-top:1px solid #e2e8f0;background:#f8fafc;font-size:11px;line-height:1.6;color:#94a3b8">ANANTTATTVA · Data Compliance<br>This is an automated workflow notification. Review and respond inside CRM.</td></tr></table></td></tr></table></body></html>`;
}
module.exports = { buildDataWorkflowEmail };
